### ISSUE TITLE
CLASSES找不到

### ISSUE THREAD

**Issue by boostlee** [puke3615/SceneClassify#5]
PATH_TRAIN_IMAGES = os.path.join(PATH_TRAIN_BASE, 'classes')
CLASSES = len(os.listdir(PATH_TRAIN_IMAGES))

Traceback (most recent call last):
  File "E:/DL/projects/SceneClassify/config.py", line 78, in <module>
    CLASSES = len(os.listdir(PATH_TRAIN_IMAGES))
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'K:/DL/data/SceneClassify/ai_challenger_scene_train_20170904\\classes'

没有classes这个目录，是不是应该读取scene_classes.csv获取CLASSES数量？

**Comment by puke3615** [comment]
README中有写的：运行split_by_class.py 脚本，分别对train数据集合val数据集进行按照子文件夹分类。
完成这一步才会有classes目录

**Comment by boostlee** [comment]
thanks a lot.

**Comment by vba34520** [comment]
手动新建一个classes文件夹
