### ISSUE TITLE
这点尤为重要！Fine-tune时松太开，可能导致训练耗时，也可能导致机器带不动；绑太紧可能导致Fixed的权重参数扼制了模型的学习能力。建议是在机器能扛得住的基础下，尽可能松绑多一些

### ISSUE THREAD

**Issue by tianlanli** [puke3615/SceneClassify#6]
你好，请问什么叫 Fine-tune 松太开与绑太紧 ，能举个例子吗

**Comment by Usernamezhx** [comment]
我的理解是A->B->C-D 每个字母代表一个层。我们用imagenet的模型finetune我们自己的网络，你要冻结一部分参数 比如 绑定ABC 松D 只让D学习。松绑太多 就是让ABCD都学习。绑的太紧就是让ABCD都不学习。不知道是不是这个意思

**Comment by tianlanli** [comment]
明白了，谢谢
